### ISSUE TITLE
Connection reset by peer (os error 104) behind corporate firewall

### ISSUE THREAD

**Issue by petr-tik** [prefix-dev/pixi#4435]
### Checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://github.com/prefix-dev/pixi/releases) of pixi, using `pixi --version`.

### Reproducible example

Cannot give a reproducible example due to the IP-restrictions at my employer. 

```shell
$ pixi install
```

### Issue description

All URLs are obfuscated. 

pixi install fails with connection errors. After several retries, it ultimately errors out with:
```
Error:   × failed to solve requirements
  ├─▶ Request failed after 3 retries
  ├─▶ error sending request for url (https://internal-conda-repo.example.com/...)
  ├─▶ client error (Connect)
  ╰─▶ Connection reset by peer (os error 104)
```
 
Standard tools like curl, wget, and conda itself work correctly in this environment, as they successfully use the system's native trust store, which includes our corporate CA certificate.

Environment

    OS: Linux
    Proxy: Corporate SSL-intercepting proxy.
    Authentication: The system is configured with the corporate CA certificate in the default trust store (e.g., ca-certificates.crt).

Troubleshooting Steps

Based on the behavior, the issue seems to be that pixi's default rustls backend does not pick up the system's trusted CA certificates. Here's what I've tried:

    Setting SSL_CERT_FILE: Exporting SSL_CERT_FILE=/path/to/my/ca-bundle.crt has no effect. Verbose logs (-vvvv) show that the TLS handshake still fails, and there's no indication that this certificate file is being loaded.
    Setting REQUESTS_CA_BUNDLE and SSL_CERT_DIR: These also have no effect.
    Using --tls-no-verify: Running pixi install --tls-no-verify also fails with the same Connection reset by peer error. This suggests the proxy itself may be dropping the connection if the client doesn't complete a valid TLS handshake, making this flag ineffective for this specific scenario.

Might be related/similar to https://github.com/prefix-dev/pixi/issues/2757

### Expected behavior

Pixi install completes successfully

**Comment by wolfv** [comment]
Hey, sorry for the long wait on this issue. Can you clarify that this is on Linux?

**Comment by wolfv** [comment]
Sorry, I overread that you mentioned that you are indeed on Linux. 

Can you elaborate whether you installed `pixi` from conda-forge or from our Github releases?

**Comment by petr-tik** [comment]
Hey, thanks for taking a look at this.

 
I installed pixi from GitHub releases. 

Version 0.52.0

**Comment by wolfv** [comment]
I tried to emulate this with mitmproxy but wasn't successful, sadly. `SSL_CERT_FILE` seems to work fine for me.

**Comment by petr-tik** [comment]
Thanks for trying to repro. 

Can you please tell me what else I can try or what information I can gather to help us get to the bottom of this?

I'm really keen to measure the possible perf gains on our large conda environment that takes 20m to resolve

**Comment by baszalmstra** [comment]
We just merged https://github.com/prefix-dev/pixi/pull/5013, are you in a position where you can build from source and try this out?

**Comment by petr-tik** [comment]
Looks promising, let me see if I can do it

**Comment by petr-tik** [comment]
The connection reset error is now gone. 

I'm getting a resolution error later, but metadata fetching works successfully now

**Comment by wolfv** [comment]
Amazing!

**Comment by scottstanie** [comment]
Sorry @petr-tik , did you do something to make this work? I started seeing this problem (also behind a firewall on linux), and updating to pixi 0.61.0 did not solve it
```
 pixi install
Error:   × failed to solve requirements of environment 'default' for platform 'linux-64'
  ├─▶   × Request failed after 3 retries
  │
  ├─▶ error sending request for url (https://conda.anaconda.org/conda-forge/noarch/repodata_shards.msgpack.zst)
  ├─▶ client error (Connect)
  ╰─▶ Connection reset by peer (os error 104)

```
